### ISSUE TITLE
Incorrect code highlighting 

### ISSUE THREAD

**Issue by ViciousDoormat** [haskell/vscode-haskell#1115] opened 2024-07-27 23:02 UTC
### Your environment

OS: Windows 11

### Steps to reproduce

This code block gets highlighted incorrectly. The word "fold" in the type definition gets highlighted blue (as a type variable) instead of yellow. When I remove "Usable a b =>" from the definition of ListCh, it gets highlighted correctly.

```haskell
data List a = No | One a | Two a (List a) deriving Show
data List_ a b = No_ | One_ a | Two_ a b 
newtype ListCh a = ListCh (forall b. Usable a b => (List_ a b -> b) -> b)

fold :: (List_ a b -> b) -> List a -> b
fold a No = a No_
fold a (One x) = a (One_ x)
fold a (Two x xs) = a (Two_ x (fold a xs))
```

![image](https://github.com/user-attachments/assets/d1a2a928-e886-4aff-91fe-e388111c5a43)

This is the whole code file (as a .txt because .hs is not supported): [list.txt](https://github.com/user-attachments/files/16401660/list.txt)

### Include debug information
When I add my extension logs, the message gets too long. If desired, I could add them to the issue as a file.

**Comment by fendor** [comment] 2024-07-29 09:55
Hi, thank you for the bug report!

I can reproduce the issue, but I think this is issue is caused by https://github.com/JustusAdam/language-haskell. By default, this vscode-haskell plugin (and HLS) do not provide the syntax highlighting.

**Comment by fendor** [comment] 2024-07-29 09:56
Perhaps this issue? https://github.com/JustusAdam/language-haskell/issues/179

**Comment by fendor** [comment] 2024-11-11 17:48
Closing as likely not our fault

**Closed by fendor** 2024-11-11 17:48 UTC
Labels: status: needs triage
