### ISSUE TITLE
Ability to disable downloading of HLS

### ISSUE THREAD

**Issue by utdemir** [haskell/vscode-haskell#294] opened 2020-09-24 00:03 UTC
I am using Nix, and usually it provides me the `haskell-language-server` executable. However, sometimes I forget to set it up properly; then `vscode-haskell` tries to download and run it, however it (expectedly) only works partially on NixOS because of some shared library errors.

So, it would be useful to me if I could be able to disable the auto-download behaviour of this extension. Simply failing when the required binary is not found should suffice.

**Comment by jneira** [comment] 2020-09-24 09:06
Thanks for the suggestion, it is somewhat a duplicate of #281 (it talks about disabling both auto downloading and auto updating) though so i will close

**Closed by jneira** 2020-09-24 09:06 UTC
