### ISSUE TITLE
Go to definition for dependencies

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/vscode-haskell#664] opened 2022-08-04 15:04 UTC
Go to definition is a useful feature. However, it works only for project's code. I would love to be able to go to definition for code that belongs to dependencies (either it is for the `base` or any other dependency that is used in the project). 

## Example usage

I have code in my project that uses the function `max` from `base`. When I try to go to defintion of the `max` function, I get the the right code file where it is defined. Next, I can go to other definitions even in that file etc.

## Example from other ecosystem
One example where I'm aware of this feature is Dart programming language (Flutter), it has all the code files downloaded in the project's directory (gitignored). It downloads all these code files once `pub get` command is run (`pub` can be understood as `cabal` in haskell world. `pub get` is also run automatically when build happens etc.).
And when trying to go to definition, it goes to the correct line to one of the relevant downloaded files present at the project's directory.

I'm curious whether there is some ongoing work that could help achieving this feature. Not sure whether this is relevant to this project, but I believe that you could point me to the right issues/projects in case it's not.

**Comment by hasufell** [comment] 2022-08-05 00:04
Duplicate of https://github.com/haskell/haskell-language-server/issues/708

This isn't in scope of the extension. The server provides these capabilities.

**Closed** 2022-08-05 00:04 UTC
Labels: upstream
