### ISSUE TITLE
Global Storage littered with old versions of HLS wrapper executables (and zips of them)

### ISSUE THREAD

**Issue by leiftw** [haskell/vscode-haskell#346] opened 2021-02-19 02:26 UTC
I'm on Windows, and `%AppData%\Code\User\globalStorage\haskell.haskell` contains files `haskell-language-server-wrapper-$version$-win32.exe(.download.zip)?`, for `$version$` being all releases of HLS since my initial installation. The executables are over 100MB and the zips another 20-odd MB. Is there a reason why old versions aren't deleted to save space?

**Comment by jneira** [comment] 2021-02-19 05:24
there is no concrete reason, you could delete all but the one you are using right now

**Comment by leiftw** [comment] 2021-02-19 14:38
Thanks for the confirmation!
I would still suggest to program the client to delete things if they are never needed and there is no reason to keep them. So yes, this was phrased as a question but also meant to suggest an improvement.

**Comment by leiftw** [comment] 2021-02-19 15:02
Actually, via the label `responsibility: client` (the meaning of which I wasn't sure about), I found this equivalent issue that's phrased more strongly ("there should be") and was tagged `enhancement`: https://github.com/haskell/vscode-haskell/issues/273

**Comment by lylek** [comment] 2021-02-25 18:49
May I humbly suggest a menu item to purge all versions except the one(s) being used in open workspaces? That way folks don't have to know the path where they're stored. They can just, maybe once a year, run the cleanup option. And if it deletes a version they need for some workspace they don't have open - no big deal, it will re-download that version when they open it.

**Comment by jneira** [comment] 2021-03-09 08:00
@lylek thanks for reporting it, i am gonna close it as somewhat duplicate of #273, copying your last suggestion there

**Closed by jneira** 2021-03-09 08:00 UTC
Labels: question, responsibility: client
