### ISSUE TITLE
Add a list of HLS executable file paths in settings

### ISSUE THREAD

**Issue by berberman** [haskell/vscode-haskell#302] opened 2020-10-05 01:59 UTC
Although it is convenient for most of us, sometimes it can be noisy. I need switch hls between few versions (dynamic linked / static linked), and hls may not appear in PATH. Opening a project, I will find that the plugin has already started downloading it, before I set the path to hls executable manually, so I have to deleted the downloaded binaries to keep it clean, even if those binaries will not make any difference in runtime.

**Comment by jneira** [comment] 2020-10-05 04:31
@berberman thanks for the suggestion, it makes totally sense. Fortunately the download is configurable in master, only left publish the extension.
(the pr closed #294, duplicate of this one)

**Comment by berberman** [comment] 2020-10-05 05:07
Perhaps maintaining a list of hls executables' paths for switching in the settings will be nice. :wink:

**Comment by jneira** [comment] 2020-10-05 05:33
That would be nice too, please change the title of the issue then (or open a new one, as you wish)

**Comment by fendor** [comment] 2022-12-05 09:15
Not relevant any more, if still a problem, please open a new issue with a new description.

**Closed by fendor** 2022-12-05 09:15 UTC
Labels: type: enhancement
